### ISSUE TITLE
Token Error Found: Error [TOKEN_INVALID]: An invalid token was provided.

### ISSUE THREAD

**Issue by aijiesd520** [17teen/7TEEN-MASS-DM-TOOL-V3#21]
Is this error related to discord token? I confirm that I put it correctly
when i run run program

**Comment by niktooutis** [comment]
npm uninstall discord.js

npm install discord.js@11.6.0

**Comment by niktooutis** [comment]
change line 81 of clientdatamanager.js as well

**Comment by Rayan570** [comment]
\Discord-Mass-DM-Tool-3revamp\script.js:80
        client.guilds.fetch(guildID).then((guild) => {
                      ^

TypeError: client.guilds.fetch is not a function
    at ScrapeUsers (C:\Users\Elève\Desktop\Discord-Mass-DM-Tool-3revamp\script.js:80:23)
    at C:\Users\Elève\Desktop\Discord-Mass-DM-Tool-3revamp\script.js:45:21
    at Interface._onLine (node:readline:485:5)
    at Interface._line (node:readline:864:8)
    at Interface._ttyWrite (node:readline:1216:14)
    at ReadStream.onkeypress (node:readline:288:10)
    at ReadStream.emit (node:events:394:28)
    at emitKeys (node:internal/readline/utils:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:61:36)


You have resolve my problem, but now i have this

**Comment by soniXx123** [comment]
Got the same problem, any results?

**Comment by Drabmarker1** [comment]
> Got the same problem, any results?

Run it on replit

**Comment by 17teen** [comment]
Use a bot token
